 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations

Numpy is a fundamental library in python for scientific computing.it offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.

 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [1]:

#np.mean()- calculate the simple arithmetic mean of an array and treats all elements equally.
#mp.average()- can also calculate the mean but allows for weighted averages,letting you assign different importance to elements.
#use np.mean() for a straightforward average and np.average() when you need to consider weights.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [2]:
import numpy as np
arr1_1d = np.array([1,2,3,4,5])
reversed_1d = arr1_1d[::-1]
print(reversed_1d)

[5 4 3 2 1]


In [5]:

#example using np.flip()

reversed_1d_flip = np.flip(arr1_1d)
print(reversed_1d_flip)

[5 4 3 2 1]


In [6]:
#reversing a 2d array
#example using slicing

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d = arr_2d[::-1, ::-1]
print(reversed_2d)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [8]:

#example using np.flip()

reversed_2d_flip = np.flip(arr_2d)
print(reversed_2d_flip)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [9]:
#We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [11]:

#data types are crucial for memory management and performance because: memory efficiency,performance,precision
#overall ,selecting the appropriate data type helps ensure efficient memory use and optimal performance.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [12]:

#Arrays are “n-dimensional” data structures that can contain all the basic Python data types, e.g., floats, integers, strings etc, but work best with numeric data. NumPy arrays (“ndarrays”) are homogenous, which means that items in the array should be of the same type.
#NumPy provides a rich set of data types that can be used to create arrays with different types of elements. The data types in NumPy are similar to, but not exactly the same as, Python data types.


 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [13]:
#Array From Existing Data" refers to the capability of creating NumPy arrays using pre-existing data structures or arrays. NumPy is a powerful numerical computing library in Python, and its arrays (ndarrays) are a fundamental data structure that allows efficient manipulation of numerical data.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [14]:
#in numpy, vstack() and hstack() are functions used to stack arrays vertically and horizontally , respectively.


In [15]:

#example of vstack()

import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
result = np.vstack((array1, array2))
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [16]:
#example of hstack()

import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])
result = np.hstack((array1, array2))
print(result)


[[1 2 5]
 [3 4 6]]


In [17]:
#vstack() stacks arrays vertically, resulting in an increase in the number of rows
#hstack() stacks arrays horizontally, resulting in an increase in the number of columns.

 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [18]:
#in numpy, fliplr() and flipud() are methods used to flip arrays along different axes.

In [19]:
#example of flipr()

import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_fliplr = np.fliplr(array2d)
print(result_fliplr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [20]:

#example of flipud()

import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6]])
result_flipud = np.flipud(array2d)
print(result_flipud)

[[4 5 6]
 [1 2 3]]


In [21]:
#effect on various array dimension
#2d arrays-fliplr() flips arrays left to right(columns reversed).
#2d arrays-flipud() flips arrays top to bottom(rows reversed)
#for 1d arrays,both methods effectively reverse the order of elements


In [22]:
#example

array1d = np.array([1, 2, 3, 4])
result_fliplr_1d = np.fliplr(array1d.reshape(-1, 1))
result_flipud_1d = np.flipud(array1d)
print(result_fliplr_1d)
print(result_flipud_1d)


[[1]
 [2]
 [3]
 [4]]
[4 3 2 1]


 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [23]:
#Splitting divides an array into multiple sub-arrays along a specified axis using functions like split, hsplit, or vsplit.
#example

In [24]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
result = np.array_split(arr, 3)
print(result)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?


In [25]:
#NumPy broadcasting is a powerful feature that allows for implicit element-wise operations between arrays of different shapes and sizes. Broadcasting automatically adjusts the shape of smaller arrays to make them compatible with larger arrays, eliminating the need for explicit looping or copying of data. This makes it easier to perform operations on arrays of different shapes, reducing the need for unnecessary duplication of data. The general rule for broadcasting is that the dimensions of the arrays must be compatible, meaning that either the dimensions are equal, or one of them is 1. NumPy automatically performs broadcasting when you perform operations between arrays that satisfy these conditions.
#vectorization in numpy means applying operations to entire arrays at once instead of using loops,which speeds up calculations.example,adding two arrays can be done directly with a+b, making it much faster


Practical Questions:

 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [26]:
import numpy as np
arr = np.random.randint(1,101,size=(3,3))
print(arr)

[[85 61 20]
 [85 10 35]
 [23 25 16]]


In [27]:

#interchange rows and columns

interchanger_arr = arr.T
print(interchanger_arr)

[[85 85 23]
 [61 10 25]
 [20 35 16]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [31]:
import numpy as np
arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
#reshape in 2x5 array
arr_2 = arr_1d.reshape(2,5)
print(arr_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
#reshape in 5x2 array
arr_3 = arr_2.reshape(5,2)
print(arr_3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [37]:
import numpy as np
arr = np.random.rand(4,4)
print(arr)

[[0.17082621 0.07589508 0.41146835 0.58761215]
 [0.12496689 0.04130792 0.68257524 0.0220317 ]
 [0.11625279 0.29724982 0.60948384 0.11418759]
 [0.37576608 0.13043538 0.59711636 0.59672766]]


In [38]:
#add a border of zeros

arr_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr_border)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.17082621 0.07589508 0.41146835 0.58761215 0.        ]
 [0.         0.12496689 0.04130792 0.68257524 0.0220317  0.        ]
 [0.         0.11625279 0.29724982 0.60948384 0.11418759 0.        ]
 [0.         0.37576608 0.13043538 0.59711636 0.59672766 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [40]:
import numpy as np
arr = np.arange(10,61,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [41]:
import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])
print(arr)


['python' 'numpy' 'pandas']


In [42]:
#applying uppercase

arr_upper = np.char.upper(arr)
print(arr_upper)


['PYTHON' 'NUMPY' 'PANDAS']


In [43]:
#applying lowercase

arr_lower = np.char.lower(arr)
print(arr_lower)

['python' 'numpy' 'pandas']


In [44]:

#applying title case

arr_title = np.char.title(arr)
print(arr_title)

['Python' 'Numpy' 'Pandas']


 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [45]:

import numpy as np
words_array = np.array(['pw','skills'])
print(words_array)

['pw' 'skills']


In [46]:

#insert a space between each word

spaced_array = np.char.join(' ', words_array)
print(spaced_array)

['p w' 's k i l l s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [47]:

import numpy as np
array1 = np.array([[2,2,3]])
array2 = np.array([[2,2,2]])
print(array1,array2)

[[2 2 3]] [[2 2 2]]


In [48]:

#perform element wise addition

print(array1+array2)

[[4 4 5]]


In [49]:
#subtraction
array1-array2

array([[0, 0, 1]])

In [51]:
#multiplication
array1*array2

array([[4, 4, 6]])

In [52]:
#Division
array1/array2

array([[1. , 1. , 1.5]])

 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [53]:

import numpy as np
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
#extract its diagonal elements

print(np.diag(arr))

[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [55]:
import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

In [56]:

import numpy as np
arr = np.random.randint(0,1001,size=100)
print(arr)


[317 343 124 246 832 356 600 680 377 397 542 200 892 657 892 539 893 930
 642 352 143 204 385 415 605 209 755 572 730 589 397 129 378 542 485 608
 663 727  62 460 502 914 683 871 103  56 712 559 814 204 607 684 488 752
 542 775 623 354 312 981 674 367 659  69 729 889 679  14  65 330 117 864
 254 735 401 298 112 812 615 183 404 464 482 886 665  43 194 279 316 905
 498 197 308 953 789 354 699 727 906 993]


In [57]:
prime_numbers = [num for num in arr if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)


Prime numbers in the array: [317, 397, 397, 727, 683, 103, 607, 367, 659, 401, 43, 197, 953, 727]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [58]:
import numpy as np
temperatures = np.random.randint(10,40,size=30)
print(temperatures)


[34 20 39 11 34 15 28 22 38 17 25 29 21 17 10 13 14 12 35 36 16 29 21 39
 14 12 34 36 12 18]


In [59]:

weekly_averages = np.array_split(temperatures,4)
print(weekly_averages)


[array([34, 20, 39, 11, 34, 15, 28, 22]), array([38, 17, 25, 29, 21, 17, 10, 13]), array([14, 12, 35, 36, 16, 29, 21]), array([39, 14, 12, 34, 36, 12, 18])]


In [60]:
weekly_averages = [np.mean(week) for week in weekly_averages]
print(weekly_averages)


[25.375, 21.25, 23.285714285714285, 23.571428571428573]
